# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
     firebase_app_distribution(
    app: "1:1030773835277:android:36f2055c8ff7f1c9c7f744",
    firebase_cli_token: "1//03XPmeV33HP1MCgYIARAAGAMSNwF-L9Irf7SbAnxliQpFDMOQIZOV206Zr7pDYU-dy4oj7fH-gpwBo9-GjWujohvWvPgNLuNRUdM",
    android_artifact_type:"APK", 
    android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
    testers:"ghazimustafa1999@gmail.com",
    release_notes:"first time fastlane"
  )
  end

end
